### ISSUE TITLE
고객 엔티티 추가

### ISSUE THREAD

**Issue by Taewoongjung** [f-lab-edu/SSKA#16]
# Issue:✨FEATURE
고객 엔티티 추가

## To-do
- [x] 고객 엔티티 추가
- [x] 고객 이름은 필수값이다.
- [x] 고객 이메일은 필수값이다.
- [x] 고객 전화번호는 필수값이다.
