### ISSUE TITLE
좌석 엔티티 추가

### ISSUE THREAD

**Issue by Taewoongjung** [f-lab-edu/SSKA#18]
# Issue:✨FEATURE
좌석 엔티티 추가

## To-do
- [x] 좌석 엔티티 추가
- [x] 좌석 번호는 필수값이다.
- [x] occupied(좌석 차지 여부)는 필수값이다.
