### ISSUE TITLE
Schedule 도메인 리팩토링

### ISSUE THREAD

**Issue by Taewoongjung** [f-lab-edu/SSKA#36]
# Issue:🔨 REFACTOR
Schedule 도메인 리팩토링

## To-do
- [x] 필드 추가 sql문 추가
- [x] ScheduleState (Enum) 추가하기
- [x] Schedule 도메인에 state 필드 추가하기
